### ISSUE TITLE
npm build error

### ISSUE THREAD

**Issue by jlrsh** [ahansrisuk/startpage#2]
I know this is probably my fault, but could you help me with the build? My log is this: 

```
0 info it worked if it ends with ok

1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]

2 info using npm@6.13.7

3 info using node@v13.9.0

4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]

5 info lifecycle startpage@0.1.0~prebuild: startpage@0.1.0

6 info lifecycle startpage@0.1.0~build: startpage@0.1.0

7 verbose lifecycle startpage@0.1.0~build: unsafe-perm in lifecycle 
true

8 verbose lifecycle startpage@0.1.0~build: PATH: /usr/lib
/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/jr/Documents/study-startpage/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

9 verbose lifecycle startpage@0.1.0~build: CWD: /home/jr/Documents/study-startpage

10 silly lifecycle startpage@0.1.0~build: Args: [ '-c', 'vue-cli-service build' ]

11 silly lifecycle startpage@0.1.0~build: Returned: code: 1  signal: null

12 info lifecycle startpage@0.1.0~build: Failed to exec build script

13 verbose stack Error: startpage@0.1.0 build: `vue-cli-service build`

13 verbose stack Exit status 1

13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)

13 verbose stack     at EventEmitter.emit (events.js:321:20)

13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)

13 verbose stack     at ChildProcess.emit (events.js:321:20)

13 verbose stack     at maybeClose (internal/child_process.js:1026:16)

13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

14 verbose pkgid startpage@0.1.0

15 verbose cwd /home/jr/Documents/study-startpage

16 verbose Linux 4.15.0-88-generic

17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"

18 verbose node v13.9.0

19 verbose npm  v6.13.7

20 error code ELIFECYCLE

21 error errno 1

22 error startpage@0.1.0 build: `vue-cli-service build`

22 error Exit status 1

23 error Failed at the startpage@0.1.0 build script.

23 error This is probably not a problem with npm. There is likely 
additional logging output above.

24 verbose exit [ 1, true ]
````

**Comment by ahansrisuk** [comment]
Hi there, I'm not the most well versed in node in general but I can try my best to assist. It looks like its failing right after line 22 when trying to run 'vue-cli-service build'.

- Make sure you ran 'npm install' in the root directory, this will make sure you have those dependencies. then try and build it again. 
- It might be failing during build because you don't have a calendar.js or auth.js for the external APIs. These are files I used to store API keys on my local machine. 
- Unlikely solution but it may be failing because you renamed the root to /study-startpage.

**Comment by jlrsh** [comment]
back after a break (long one lmao), which calendar.js and auth.js did you use? Don't want to mess this up cuz I've had a ton of trouble with this specific build.

**Comment by jlrsh** [comment]
bump, could you send a sample calendar.js and auth.js?

**Comment by ahansrisuk** [comment]
I don't think your build issue is related to not having the files stated. I no longer have a sample calendar.js file but looking back on the code it should just be in this format:
`export default {
  ids = []
}`

Where ids is an array of your Google Calendars. Auth on the other hand should look something like this
`export default {
    darksky: '',
    api_key: '',
    client_id: '',
    scopes: ''
}`

Where the empty strings are your specific API keys. Darksky is for the weather functionality and the others are for your Google calendars
